[package]
name = "basic-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "^1", features = ["derive"] }
config = "^0"
tokio = { version = "^1", features = ["full"] }
axum = "^0"