on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --verbose
      - run: cargo test --verbose